name: prettychord
title: Pretty Chord
base: core22
adopt-info: prettychord
icon: data/icons/hicolor/scalable/apps/com.example.prettychord.svg
summary: A chord sheet editor and viewer
description: |
  PrettyChord is a GTK4 application to write chords using ChordPro syntax
  and generate beautiful PDF files.

grade: stable
confinement: strict

parts:
  prettychord:
    plugin: meson
    source: .
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=0 | sed 's/^v//')
    meson-parameters:
      - --prefix=/usr
    build-packages:
      - libgtk-4-dev
      - libgee-0.8-dev
      - libcairo2-dev
      - libgtksourceview-5-dev
      - valac
      - pkg-config
    stage-packages:
      - libgtk-4-1
      - libgee-0.8-2
      - libcairo2
      - libgtksourceview-5-0

apps:
  prettychord:
    command: usr/bin/prettychord
    extensions: [gnome]
    common-id: com.example.prettychord
    desktop: usr/share/applications/com.example.prettychord.desktop
    plugs:
      - home
      - removable-media
